import type { ArsipAkashiSectionContract, ArsipAkashiSectionId } from "./contracts";
import type { CanonicalSystemId } from "./types";

const ALL_SYSTEMS: CanonicalSystemId[] = [
  "numerology",
  "human-design",
  "natal-chart",
  "destiny-matrix",
  "weton",
  "bazi",
  "vedic-astrology",
  "tzolkin",
  "whole-sign",
  "astrocartography",
  "zi-wei-dou-shu",
];

export const ARSIP_AKASHI_SOURCE_LEDGER: Record<ArsipAkashiSectionId, ArsipAkashiSectionContract> = {
  "soul-identity": {
    sectionId: "soul-identity",
    eligibleSystems: [
      "numerology",
      "human-design",
      "natal-chart",
      "destiny-matrix",
      "bazi",
      "vedic-astrology",
      "tzolkin",
      "zi-wei-dou-shu",
    ],
    contributionPriority: [
      "human-design",
      "destiny-matrix",
      "numerology",
      "natal-chart",
      "bazi",
    ],
    allowedDomains: ["identity", "karma", "growth", "spirituality"],
    required: true,
    birthTimeSensitive: true,
    classification: "calculated",
    fallbackPolicy: "reduce-confidence",
  },
  "energy-mechanics": {
    sectionId: "energy-mechanics",
    eligibleSystems: [
      "human-design",
      "natal-chart",
      "bazi",
      "vedic-astrology",
      "whole-sign",
    ],
    contributionPriority: ["human-design", "natal-chart", "bazi"],
    allowedDomains: ["mechanics", "identity"],
    required: true,
    birthTimeSensitive: true,
    classification: "calculated",
    fallbackPolicy: "reduce-confidence",
  },
  "wounds-shadow-lineage": {
    sectionId: "wounds-shadow-lineage",
    eligibleSystems: [
      "destiny-matrix",
      "human-design",
      "natal-chart",
      "bazi",
      "vedic-astrology",
      "tzolkin",
      "numerology",
    ],
    contributionPriority: ["destiny-matrix", "human-design", "natal-chart"],
    allowedDomains: ["shadow", "karma", "growth"],
    required: true,
    birthTimeSensitive: false,
    classification: "calculated",
    fallbackPolicy: "reduce-confidence",
  },
  "work-talents": {
    sectionId: "work-talents",
    eligibleSystems: [
      "human-design",
      "destiny-matrix",
      "numerology",
      "natal-chart",
      "bazi",
      "vedic-astrology",
      "tzolkin",
      "whole-sign",
      "zi-wei-dou-shu",
    ],
    contributionPriority: [
      "human-design",
      "destiny-matrix",
      "numerology",
      "natal-chart",
    ],
    allowedDomains: ["talents", "resources", "identity"],
    required: true,
    birthTimeSensitive: false,
    classification: "calculated",
    fallbackPolicy: "reduce-confidence",
  },
  "love-relationships": {
    sectionId: "love-relationships",
    eligibleSystems: [
      "human-design",
      "natal-chart",
      "destiny-matrix",
      "bazi",
      "vedic-astrology",
      "tzolkin",
      "zi-wei-dou-shu",
    ],
    contributionPriority: ["human-design", "natal-chart", "destiny-matrix"],
    allowedDomains: ["relationships", "shadow", "growth"],
    required: true,
    birthTimeSensitive: false,
    classification: "calculated",
    fallbackPolicy: "reduce-confidence",
  },
  "body-environment": {
    sectionId: "body-environment",
    eligibleSystems: [
      "human-design",
      "natal-chart",
      "bazi",
      "vedic-astrology",
      "whole-sign",
    ],
    contributionPriority: ["human-design", "natal-chart", "bazi"],
    allowedDomains: ["health", "mechanics", "identity"],
    required: false,
    birthTimeSensitive: true,
    classification: "calculated",
    fallbackPolicy: "omit-section",
  },
  "spirituality-evolution": {
    sectionId: "spirituality-evolution",
    eligibleSystems: [
      "human-design",
      "natal-chart",
      "destiny-matrix",
      "tzolkin",
      "zi-wei-dou-shu",
      "numerology",
    ],
    contributionPriority: ["human-design", "destiny-matrix", "tzolkin"],
    allowedDomains: ["spirituality", "growth", "karma"],
    required: false,
    birthTimeSensitive: false,
    classification: "calculated",
    fallbackPolicy: "omit-section",
  },
  "current-life-phase": {
    sectionId: "current-life-phase",
    eligibleSystems: [
      "natal-chart",
      "human-design",
      "destiny-matrix",
      "bazi",
      "vedic-astrology",
      "numerology",
      "astrocartography",
      "zi-wei-dou-shu",
    ],
    contributionPriority: ["natal-chart", "human-design", "destiny-matrix", "bazi"],
    allowedDomains: ["timing", "location", "growth"],
    required: true,
    birthTimeSensitive: true,
    classification: "calculated",
    fallbackPolicy: "reduce-confidence",
  },
  "symbolic-origin": {
    sectionId: "symbolic-origin",
    eligibleSystems: [
      "natal-chart",
      "destiny-matrix",
      "bazi",
      "tzolkin",
      "astrocartography",
      "zi-wei-dou-shu",
      "vedic-astrology",
    ],
    contributionPriority: ["natal-chart", "destiny-matrix", "bazi"],
    allowedDomains: ["karma", "spirituality", "identity"],
    required: false,
    birthTimeSensitive: false,
    classification: "symbolic",
    fallbackPolicy: "omit-section",
  },
  "growth-potential": {
    sectionId: "growth-potential",
    eligibleSystems: ALL_SYSTEMS,
    contributionPriority: ALL_SYSTEMS,
    allowedDomains: ["growth", "spirituality", "talents"],
    required: true,
    birthTimeSensitive: false,
    classification: "cross-system-synthesis",
    fallbackPolicy: "reduce-confidence",
  },
};

export const ELIGIBLE_SYSTEMS_PER_SECTION: Record<ArsipAkashiSectionId, number> =
  Object.fromEntries(
    Object.entries(ARSIP_AKASHI_SOURCE_LEDGER).map(
      ([id, contract]) => [id, contract.eligibleSystems.length],
    ),
  ) as Record<ArsipAkashiSectionId, number>;
