export const SERVER_OWNED_ACCESS_FIELDS = [
  "plan",
  "plans",
  "planLabel",
  "tier",
  "tiers",
  "role",
  "roles",
  "guardianRole",
  "adminRole",
  "badge",
  "badges",
  "testerBadge",
  "guardianBadge",
  "recognitionTier",
  "recognitionDate",
  "guardianCandidate",
  "guardianApproved",
  "guardianApprovedAt",
  "guardianApprovedBy",
  "isInternalTester",
  "excludeFromAdminAnalytics",
  "internalTesterLabel",
  "isDeveloper",
  "isFoundingMember",
  "founder",
  "inti",
  "alfa",
  "admin",
  "staff",
  "premium",
  "isPremium",
  "effectiveTier",
  "premiumExpiresAt",
  "paid",
  "paidUntil",
  "paymentStatus",
  "subscription",
  "subscriptions",
  "subscriptionStatus",
  "subscriptionState",
  "entitlement",
  "entitlements",
  "entitlementSource",
  "entitlementUpdatedAt",
  "membership",
  "membershipType",
  "memberType",
  "membershipStartDate",
  "membershipExpiryDate",
  "membershipExpiresAt",
  "billing",
  "billingVerified",
  "purchase",
  "purchases",
  "purchaseState",
  "purchaseTokenHash",
  "productId",
  "basePlanId",
  "packageName",
  "provider",
  "tokenHash",
  "ackStatus",
  "googlePlay",
  "expiryDate",
  "expiresAt",
  "accessStart",
  "accessUntil",
  "accessSource",
  "accessSourceVersion",
  "validUntil",
  "trial",
  "trialStartedAt",
  "trialEndsAt",
  "trialLoginCount",
  "trialStatus",
  "trialCompletedAt",
  "lastSuccessfulLoginAt",
  "quota",
  "limits",
  "credits",
  "updatedBy",
] as const;

const SERVER_OWNED_ACCESS_FIELD_SET = new Set<string>(SERVER_OWNED_ACCESS_FIELDS);

export function stripServerOwnedAccessFields<T extends Record<string, unknown>>(data: T): Partial<T> {
  return Object.fromEntries(
    Object.entries(data).filter(([key]) => !SERVER_OWNED_ACCESS_FIELD_SET.has(key)),
  ) as Partial<T>;
}
