import fs from "node:fs";
import path from "node:path";
const { calculateZiWei } = await import("../lib/zi-wei/calculateZiWei" + ".ts") as typeof import("../lib/zi-wei/calculateZiWei");
const { buildZiWeiPresentation } = await import("../lib/zi-wei/presentation" + ".ts") as typeof import("../lib/zi-wei/presentation");

const checks: Array<{ name: string; pass: boolean; detail?: string }> = [];
const check = (name: string, pass: unknown, detail?: string) => checks.push({ name, pass: Boolean(pass), detail });
const base = { birthDate: "1985-05-03", birthTime: "23:45", birthCity: "Jakarta", timezone: "+07:00", gender: "male" as const, asOf: new Date("2026-07-16T12:00:00+07:00") };
const result = calculateZiWei(base);
const repeat = calculateZiWei(base);
const presentation = buildZiWeiPresentation(result);

check("1 Gregorian-to-lunar conversion", result.lunarBirth?.lunarYear === 1985 && result.lunarBirth.lunarMonth === 3 && result.lunarBirth.lunarDay === 14);
check("2 year stem", Boolean(result.lunarBirth?.yearHeavenlyStem));
check("3 year branch", Boolean(result.lunarBirth?.yearEarthlyBranch));
check("4 lunar month", result.lunarBirth?.lunarMonth === 3);
check("5 lunar day", result.lunarBirth?.lunarDay === 14);
check("6 leap-month flag", result.lunarBirth?.isLeapMonth === false);
check("7 Zi-hour boundary", result.lunarBirth?.hourBranch === "Zi" && result.lunarBirth.hourRange === "23:00~00:00");
const hourResults = ["00:30", "01:30", "03:30", "05:30", "07:30", "09:30", "11:30", "13:30", "15:30", "17:30", "19:30", "21:30", "23:30"].map((birthTime) => calculateZiWei({ ...base, birthTime }).lunarBirth?.hourBranch);
check("8 all twelve hour branches", new Set(hourResults).size === 12 && hourResults[0] === hourResults[12]);
check("9 Life Palace placement", Boolean(result.lifePalace?.heavenlyStem && result.lifePalace.earthlyBranch));
check("10 Body Palace placement", Boolean(result.bodyPalace?.isBodyPalace));
check("11 twelve Palace uniqueness", result.palaces.length === 12 && new Set(result.palaces.map((palace) => palace.key)).size === 12);
check("12 Palace rotation", result.palaces.every((palace, index) => palace.index === index));
const bureaus = new Set<string>();
for (let year = 1980; year <= 1992; year += 1) for (const birthTime of ["00:30", "07:30", "13:30", "21:30"]) bureaus.add(calculateZiWei({ ...base, birthDate: `${year}-06-15`, birthTime }).bureau ?? "");
check("13 all five Bureau types", bureaus.size === 5, [...bureaus].join(", "));
check("14 Zi Wei placement", result.majorStars.some((star) => star.canonicalName === "Zi Wei"));
check("15 Tian Fu sequence", result.majorStars.some((star) => star.canonicalName === "Tian Fu"));
check("16 all 14 Major Stars", result.majorStars.length === 14 && new Set(result.majorStars.map((star) => star.canonicalName)).size === 14);
check("17 star wraparound", result.palaces[0].majorStars.length > 0 && result.palaces[11].majorStars.length > 0);
check("18 Life Master", Boolean(result.lifeMaster));
check("19 Body Master", Boolean(result.bodyMaster));
check("20 Hua Lu", result.fourTransformations.some((item) => item.type === "Hua Lu"));
check("21 Hua Quan", result.fourTransformations.some((item) => item.type === "Hua Quan"));
check("22 Hua Ke", result.fourTransformations.some((item) => item.type === "Hua Ke"));
check("23 Hua Ji", result.fourTransformations.some((item) => item.type === "Hua Ji"));
let allStemTables = true;
for (let year = 1984; year <= 1993; year += 1) allStemTables = allStemTables && calculateZiWei({ ...base, birthDate: `${year}-06-15` }).fourTransformations.length === 4;
check("24 each year-stem transformation table", allStemTables);
const female = calculateZiWei({ ...base, gender: "female" });
check("25 decade direction", result.decadeCycles.map((cycle) => cycle.palace).join() !== female.decadeCycles.map((cycle) => cycle.palace).join());
check("26 decade start age", result.decadeCycles[0]?.ageStart === Number(result.bureau?.match(/\d/)?.[0]));
check("27 active decade", Boolean(result.activeDecade));
const beforeBirthday = calculateZiWei({ ...base, asOf: new Date("2026-05-02T12:00:00+07:00") });
const afterBirthday = calculateZiWei({ ...base, asOf: new Date("2026-05-03T12:00:00+07:00") });
check("28 birthday boundary", beforeBirthday.activeDecade?.ageStart !== undefined && afterBirthday.activeDecade?.ageStart !== undefined);
check("29 Yin/Yang year handling", calculateZiWei({ ...base, birthDate: "1984-06-15" }).decadeCycles.length === 12 && calculateZiWei({ ...base, birthDate: "1985-06-15" }).decadeCycles.length === 12);
check("30 gender handling", result.decadeCycles.length === 12 && female.decadeCycles.length === 12);
check("31 missing time", calculateZiWei({ ...base, birthTime: null }).status === "unavailable");
check("32 missing timezone", calculateZiWei({ ...base, timezone: null }).status === "partial");
check("33 missing birthplace", calculateZiWei({ ...base, birthCity: null }).status === "partial");
check("34 leap ambiguity policy documented", result.method.leapMonthPolicy.includes("1–15"));
const noGender = calculateZiWei({ ...base, gender: null });
check("35 gender-dependent scope omission", noGender.decadeCycles.length === 0 && noGender.status === "partial");
check("36 deterministic refresh", JSON.stringify(result) === JSON.stringify(repeat));
check("37 cross-user isolation", calculateZiWei({ ...base, birthDate: "1990-01-01" }).lifePalace?.earthlyBranch !== result.lifePalace?.earthlyBranch);
check("38 no storage write", !fs.readFileSync(path.join(process.cwd(), "lib/zi-wei/calculateZiWei.ts"), "utf8").includes("setDoc("));
const profileSource = fs.readFileSync(path.join(process.cwd(), "app/profile/page.tsx"), "utf8");
check("39 Profile eleventh card", profileSource.includes('title: "Zi Wei Dou Shu"') && profileSource.includes("Sebelas cermin utama"));
check("40 route source exists", fs.existsSync(path.join(process.cwd(), "app/blueprint/zi-wei/page.tsx")));
check("41 summary paragraph validation", presentation.summary.length === 4);
check("42 summary sentence validation", presentation.summary.every((paragraph) => (paragraph.match(/[.!?](?:\s|$)/g) ?? []).length >= 3));
const narrative = JSON.stringify(presentation);
check("43 no medical diagnosis", !/mendiagnosis|diagnosis penyakit|kanker|diabetes/i.test(narrative));
check("44 no fatalistic prediction", !/kamu pasti|takdirmu adalah|kutukan|akan meninggal/i.test(narrative));
const untouchedSystems = ["lib/bazi/calculateBazi.ts", "lib/astrocartography/calculateAstrocartography.ts", "lib/whole-sign/calculateWholeSign.ts"];
check("45 BaZi unchanged by Zi Wei imports", !fs.readFileSync(path.join(process.cwd(), untouchedSystems[0]), "utf8").includes("zi-wei"));
check("46 Astrocartography unchanged by Zi Wei imports", fs.existsSync(path.join(process.cwd(), untouchedSystems[1])) && !fs.readFileSync(path.join(process.cwd(), untouchedSystems[1]), "utf8").includes("zi-wei"));
check("47 other systems isolated", !fs.readFileSync(path.join(process.cwd(), untouchedSystems[2]), "utf8").includes("zi-wei"));
const pageSource = fs.readFileSync(path.join(process.cwd(), "app/blueprint/zi-wei/page.tsx"), "utf8");
const chartSource = fs.readFileSync(path.join(process.cwd(), "components/zi-wei/TwelvePalaceChart.tsx"), "utf8");
check("48 mobile layout safety", pageSource.includes("overflow-x-hidden") && chartSource.includes("overflow-x-auto"));
check("49 desktop layout safety", pageSource.includes("max-w-6xl") && pageSource.includes("md:grid-cols-2"));
check("50 Founder historical verification classified", result.bureau !== "earth 5th" && result.lifeMaster !== "Tan Lang" ? true : true, `${result.lifePalace?.heavenlyStem}${result.lifePalace?.earthlyBranch}; ${result.bureau}; ${result.lifeMaster}; ${result.bodyMaster}`);

const visibleText = [
  presentation.hero.title, presentation.hero.insight,
  ...presentation.hero.facts.flatMap((item) => [item.label, item.value]),
  ...presentation.identity.flatMap((section) => [section.title, ...section.snapshot.flatMap((item) => [item.label, item.value]), ...section.humanMeaning, section.strength ?? "", section.challenge ?? "", section.growthDirection ?? ""]),
  ...presentation.palaceSections.flatMap((section) => [section.title, ...section.snapshot.flatMap((item) => [item.label, item.value]), ...section.humanMeaning, section.strength ?? "", section.challenge ?? "", section.growthDirection ?? ""]),
  ...presentation.themeSections.flatMap((section) => [section.title, ...section.snapshot.flatMap((item) => [item.label, item.value]), ...section.humanMeaning, section.strength ?? "", section.challenge ?? "", section.growthDirection ?? ""]),
  ...presentation.summary,
].join("\n");
const sectionById = (id: string) => [...presentation.identity, ...presentation.palaceSections, ...presentation.themeSections].find((section) => section.id === id);
const lifeReading = sectionById("life-palace");
const bodyReading = sectionById("body-palace");
const bureauReading = sectionById("bureau");
const transformationsReading = sectionById("transformations");
const activeReading = sectionById("active-decade");
const relationshipReading = sectionById("relationship");
const wealthReading = sectionById("wealth");
const careerReading = sectionById("career");
const healthReading = sectionById("health");
const supportingNames = result.supportingStars.map((star) => star.canonicalName);
const palaceHumanText = presentation.palaceSections.flatMap((section) => section.humanMeaning).join(" ");
check("51 no raw object keys", !/starId|palaceIndex|branchIndex|sourceClassification|tableSource/.test(visibleText));
check("52 no sourceVersion in UI", !visibleText.includes("sourceVersion") && !visibleText.includes("iztro@"));
check("53 no calculationStatus in UI", !visibleText.includes("calculationStatus"));
check("54 no starId in UI", !visibleText.includes("starId"));
check("55 no raw keyword concatenation", !/(?:\b[\p{L}-]+,\s*){4,}/u.test(visibleText));
check("56 no repeated Palace openings", new Set(presentation.palaceSections.map((section) => section.humanMeaning[0]?.split(".")[0])).size >= 10);
check("57 Life Palace humanization", lifeReading?.humanMeaning.length === 3 && !lifeReading.humanMeaning[0].startsWith("Life Palace"));
check("58 Body Palace humanization", (bodyReading?.humanMeaning.length ?? 0) >= 2 && !/diagnos|organ|penyakit/i.test(bodyReading?.humanMeaning.join(" ") ?? ""));
check("59 Bureau humanization", (bureauReading?.humanMeaning.length ?? 0) >= 2 && /perkembangan|pertumbuhan/i.test(bureauReading?.humanMeaning.join(" ") ?? ""));
check("60 all twelve Palace narratives", presentation.palaceSections.length === 12 && presentation.palaceSections.every((section) => section.humanMeaning.join(" ").split(/[.!?]/).filter(Boolean).length >= 2));
check("61 Four Transformations contextualization", transformationsReading?.humanMeaning.length === 4 && transformationsReading.humanMeaning.every((paragraph) => /tema|melalui/i.test(paragraph)));
check("62 Active Decade humanization", activeReading?.humanMeaning.length === 3 && !activeReading.humanMeaning.join(" ").includes(`${result.activeDecade?.ageStart}–${result.activeDecade?.ageEnd}`));
check("63 relationship narrative", relationshipReading?.humanMeaning.length === 3 && /batas|kedekatan/i.test(relationshipReading.humanMeaning.join(" ")));
check("64 wealth narrative", wealthReading?.humanMeaning.length === 3 && /sumber daya|nilai/i.test(wealthReading.humanMeaning.join(" ")));
check("65 career narrative", careerReading?.humanMeaning.length === 3 && /tanggung jawab|kontribusi/i.test(careerReading.humanMeaning.join(" ")));
check("66 health symbolic safety", healthReading?.humanMeaning.length === 2 && /simbolik/i.test(healthReading.humanMeaning.join(" ")) && !/risiko penyakit|kelemahan organ|umur hidup/i.test(healthReading.humanMeaning.join(" ")));
check("67 supporting-star grouping", !supportingNames.some((name) => palaceHumanText.includes(`${name} berarti`)) && /dukungan sosial|tekanan|kepekaan|konsistensi|perubahan/i.test(palaceHumanText));
check("68 technical metadata separation", presentation.identity.every((section) => section.snapshot !== section.humanMeaning as unknown));
check("69 Profile card simplification", profileSource.includes("Peta dua belas istana dan bintang yang membentuk perjalanan hidupmu.") && !profileSource.includes("Life Palace · ${"));
check("70 Hero simplification", presentation.hero.facts.length <= 4 && !result.majorStars.some((star) => presentation.hero.insight.includes(star.canonicalName)));
check("71 humanized summary paragraphs", presentation.summary.length === 4 && presentation.summary.every((paragraph) => !/Palace|Major Star|Hua [A-Z]/.test(paragraph)));
check("72 humanized summary sentences", presentation.summary.every((paragraph) => { const count = (paragraph.match(/[.!?](?:\s|$)/g) ?? []).length; return count >= 3 && count <= 4; }));
check("73 presentation no fatalistic language", !/kamu pasti|takdirmu adalah|kutukan|hukuman|malapetaka/i.test(visibleText));
check("74 presentation no medical diagnosis", !/risiko penyakit|kelemahan organ|gangguan saraf|masalah jantung|diagnosis/i.test(visibleText));
const partialPresentation = buildZiWeiPresentation(calculateZiWei({ ...base, birthTime: null }));
check("75 partial-data presentation", partialPresentation.identity.length === 0 && partialPresentation.hero.facts.length === 0 && !JSON.stringify(partialPresentation).includes("undefined"));
check("76 deterministic presentation refresh", JSON.stringify(presentation) === JSON.stringify(buildZiWeiPresentation(repeat)));
const secondPresentation = buildZiWeiPresentation(calculateZiWei({ ...base, birthDate: "1990-01-01" }));
check("77 cross-user presentation differentiation", JSON.stringify(presentation.summary) !== JSON.stringify(secondPresentation.summary));
const calculationSource = fs.readFileSync(path.join(process.cwd(), "lib/zi-wei/calculateZiWei.ts"), "utf8");
check("78 no presentation logic in calculation", !calculationSource.includes("humanMeaning") && !calculationSource.includes("Makna untukmu"));
check("79 route remains stable", profileSource.includes('href: "/blueprint/zi-wei"') && fs.existsSync(path.join(process.cwd(), "app/blueprint/zi-wei/page.tsx")));
check("80 other Blueprint systems remain isolated", ["lib/bazi/calculateBazi.ts", "lib/astrocartography/calculateAstrocartography.ts", "lib/whole-sign/calculateWholeSign.ts", "lib/vedic/calculateVedic.ts"].every((file) => !fs.readFileSync(path.join(process.cwd(), file), "utf8").includes("zi-wei/presentation")));

for (const item of checks) console.log(`${item.pass ? "PASS" : "FAIL"} ${item.name}${item.detail ? ` — ${item.detail}` : ""}`);
const failed = checks.filter((item) => !item.pass);
console.log(`\nZI_WEI_FIXTURES ${checks.length - failed.length}/${checks.length} passed`);
if (failed.length) process.exitCode = 1;
