const SUPPORT_CATEGORIES = ['SUGGESTION', 'BUG_REPORT', 'GENERAL_FEEDBACK', 'ACCOUNT_SUPPORT'] as const;
if (SUPPORT_CATEGORIES.length !== 4 || new Set(SUPPORT_CATEGORIES).size !== 4) throw new Error('INBOX_COMPOSE_CATEGORIES_FAIL');
console.log('INBOX_COMPOSE_CATEGORIES_PASS');
