import { readFileSync } from "node:fs";
import { calculateBhumiMatrix } from "../lib/engines/calculateBhumiMatrix";
import { buildDestinyMatrixPresentation } from "../lib/destiny-matrix/presentation";
import { DESTINY_MATRIX_GOLDEN_FIXTURES } from "../lib/engines/destinyMatrixGoldenFixtures";
import { DESTINY_MATRIX_AGE_CYCLE, DESTINY_MATRIX_NODES, DESTINY_MATRIX_PATHS, DESTINY_MATRIX_VISUAL_EDGES } from "../lib/destiny-matrix/topology";

type Result = { name: string; passed: boolean; detail: string };
const results: Result[] = [];
const check = (name: string, passed: boolean, detail: string) => results.push({ name, passed, detail });
const equal = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right);
const sentenceCount = (text: string) => text.split(/[.!?]+(?=\s|$)/).map((part) => part.trim()).filter(Boolean).length;

const founder = calculateBhumiMatrix("1985-05-03");
const presentation = buildDestinyMatrixPresentation(founder);
const pageSource = readFileSync("app/blueprint/destiny-matrix/page.tsx", "utf8");
const diagramSource = readFileSync("components/blueprint/DestinyMatrixVisual.tsx", "utf8");
const projectionSource = readFileSync("lib/engines/destinyMatrixProjection.ts", "utf8");
const profileSource = readFileSync("app/profile/page.tsx", "utf8");
const graphSource = readFileSync("lib/engines/destinyMatrixGraph.ts", "utf8");
const legacySource = readFileSync("lib/calculations/destinyMatrix/energy.ts", "utf8");

check("single topology owner", !/const\s+decadeNodeIds/.test(`${pageSource}\n${diagramSource}`) && diagramSource.includes("DESTINY_MATRIX_TOPOLOGY.diagramGroups") && projectionSource.includes("topologyNodeIds"), "page, diagram, and projections consume topology");
check("canonical node IDs", DESTINY_MATRIX_NODES.length === 32 && new Set(DESTINY_MATRIX_NODES.map((node) => node.nodeId)).size === 32 && DESTINY_MATRIX_NODES.every((node) => /^BM\d{2}$/.test(node.nodeId)), "32 stable structural IDs");
check("Common Energy order", equal(presentation.commonEnergy.nodeIds, ["BM05", "BM23", "BM24"]) && presentation.commonEnergy.displayValue === "8–7–15", presentation.commonEnergy.displayValue);
check("Love Path order", equal(presentation.lovePath.nodeIds, ["BM20", "BM21", "BM10"]) && presentation.lovePath.displayValue === "7–10–21", presentation.lovePath.displayValue);
check("Money Path order", equal(presentation.moneyPath.nodeIds, ["BM03", "BM16", "BM11", "BM22", "BM20"]) && presentation.moneyPath.displayValue === "5–18–13–20–7", presentation.moneyPath.displayValue);
check("Karmic Tile order", equal(presentation.karmicTile.nodeIds, ["BM10", "BM17", "BM04"]) && presentation.karmicTile.displayValue === "21–7–13", presentation.karmicTile.displayValue);
check("Father Talents deferred", presentation.fatherTalents === null, "conflicting ancestral ownership is not displayed");
check("Mother Talents deferred", presentation.motherTalents === null, "conflicting ancestral ownership is not displayed");
check("Higher Talents order", presentation.higherTalents.displayValue === "5–18–13", presentation.higherTalents.displayValue);
check("main Love Arcana", presentation.lovePath.mainNodeId === "BM21" && presentation.lovePath.mainArcana === 10, String(presentation.lovePath.mainArcana));
check("main Money Arcana", presentation.moneyPath.mainNodeId === "BM22" && presentation.moneyPath.mainArcana === 20, String(presentation.moneyPath.mainArcana));
check("Father Line projection", presentation.fatherLine?.talent.displayValue === "8–6–16" && presentation.fatherLine.karma.displayValue === "8–8–18", `${presentation.fatherLine?.talent.displayValue} / ${presentation.fatherLine?.karma.displayValue}`);
check("Mother Line projection", presentation.motherLine?.talent.displayValue === "10–10–18" && presentation.motherLine.karma.displayValue === "6–22–16", `${presentation.motherLine?.talent.displayValue} / ${presentation.motherLine?.karma.displayValue}`);
check("diagonal versus lineage", DESTINY_MATRIX_PATHS.FATHER_VISUAL_DIAGONAL.orderedNodeIds.length === 7 && DESTINY_MATRIX_PATHS.MOTHER_VISUAL_DIAGONAL.orderedNodeIds.length === 7 && presentation.fatherLine !== null && presentation.motherLine !== null, "visual diagonals and dedicated three-value projections coexist");
check("position-aware Arcana", presentation.commonEnergy.values.includes(15), "Common Energy retains position-owned Arcana 15");
check("diagram node integrity", presentation.diagram.nodes.length === 32 && presentation.diagram.nodes.every((node) => founder.graph.nodes.some((source) => source.id === node.arcanaSource && source.value === node.value)), "all displayed values resolve by node ID");
const diagramIds = new Set(presentation.diagram.nodes.map((node) => node.nodeId));
check("diagram edge integrity", DESTINY_MATRIX_VISUAL_EDGES.length > 0 && DESTINY_MATRIX_VISUAL_EDGES.every((edge) => diagramIds.has(edge.fromNodeId) && diagramIds.has(edge.toNodeId)), `${DESTINY_MATRIX_VISUAL_EDGES.length} valid edges`);
check("no duplicated topology constants", !/["']BM(?:05|20|21|22|23|24)["']\s*,\s*["']BM/.test(`${pageSource}\n${diagramSource}`), "no active route arrays in page or SVG");
check("no array-index placement", !/coordinate.*index|x:\s*.*index|y:\s*.*index/.test(diagramSource), "diagram reads canonical coordinates");
check("Yearly Arcana ring", /ARCANA TAHUNAN/.test(diagramSource) && diagramSource.includes("renderAgePerimeter") && diagramSource.includes("activeAnnualArcana"), "yearly values, ages, and active value are rendered");
check("approved Age Cycle mapping", DESTINY_MATRIX_AGE_CYCLE.status === "founder_approved_visual_mapping" && DESTINY_MATRIX_AGE_CYCLE.segments.length === 8 && DESTINY_MATRIX_AGE_CYCLE.points.length === 7 && presentation.ageCycle === null, "visual-only eight-decade mapping; presentation calculation remains separate");
check("partial-data omission", pageSource.includes("presentation.fatherLine &&") && pageSource.includes("presentation.motherLine &&") && pageSource.includes("presentation.fatherTalents &&") && pageSource.includes("presentation.motherTalents &&"), "optional lineage sections are conditional");
check("summary paragraph count", presentation.summary.length === 4, String(presentation.summary.length));
check("summary sentence count", presentation.summary.every((paragraph) => sentenceCount(paragraph) >= 3 && sentenceCount(paragraph) <= 4), presentation.summary.map(sentenceCount).join(","));
check("summary raw Arcana exclusion", presentation.summary.every((paragraph) => !/\d/.test(paragraph)), "no digits");
const forbiddenSummaryTerms = /Center Arcana|Common Energy|Karmic Tile|Love Path|Money Path|Father Line|Mother Line|Father Talents|Mother Talents|Higher Talents|Arcana|matrix|energi angka/i;
check("summary technical-label exclusion", presentation.summary.every((paragraph) => !forbiddenSummaryTerms.test(paragraph)), "no matrix labels");
const differentiated = DESTINY_MATRIX_GOLDEN_FIXTURES.map((fixture) => buildDestinyMatrixPresentation(calculateBhumiMatrix(fixture.dateOfBirth)).summary.join("\n"));
check("cross-user differentiation", new Set(differentiated).size === DESTINY_MATRIX_GOLDEN_FIXTURES.length, `${new Set(differentiated).size} unique summaries`);
const refreshA = buildDestinyMatrixPresentation(calculateBhumiMatrix("1985-05-03"));
const refreshB = buildDestinyMatrixPresentation(calculateBhumiMatrix("1985-05-03"));
check("deterministic refresh", equal(refreshA, refreshB), "presentation stable for the same input");
check("read-only page", !/saveUser|setDoc|addDoc|updateDoc|\.save\(/.test(pageSource), "no write operation");
check("cross-user isolation", !/localStorage|sessionStorage/.test(pageSource) && pageSource.includes("getUserBlueprint") && pageSource.includes("getUserProfile"), "active authenticated storage reads only");
check("no calculation changes", graphSource.includes('add("BM25", "derived", ["BM06", "BM23"]') && graphSource.includes('add("BM31", "derived", ["BM09", "BM23"]') && legacySource.includes("fpoint + upoint") && legacySource.includes("ipoint + upoint"), "restored BM25-BM32 parents preserved");
check("mobile source safety", /grid-cols-1|flex-wrap|max-w-full/.test(`${pageSource}\n${diagramSource}`), "single-column and bounded SVG source present");
check("desktop source safety", /md:grid-cols-2|md:grid-cols-3|sm:p-8/.test(pageSource), "responsive desktop grids present");
check("Profile card parity", profileSource.includes('title: "Destiny Matrix"') && profileSource.includes('desc: "Pola energi, pelajaran, dan potensi yang membentuk perjalananmu."') && !/destinyCard\.(?:center|commonEnergy|insight|action)/.test(profileSource), "Destiny card uses the same title-and-description contract as the other seven systems");
check("route integration", pageSource.includes("buildDestinyMatrixPresentation") && pageSource.includes("MatrixDiagram"), "route consumes adapter and preserved Build 72 diagram");
check("principal narrative length", [presentation.center, presentation.commonEnergy, presentation.karmicTile, presentation.lovePath, presentation.moneyPath, presentation.higherTalents].every((item) => sentenceCount(item.narrative) >= 2 && sentenceCount(item.narrative) <= 3), "all available principal cards contain two or three sentences");

const failed = results.filter((result) => !result.passed);
console.log(JSON.stringify({ status: failed.length ? "failed" : "passed", summary: { passed: results.length - failed.length, failed: failed.length }, failures: failed, results }, null, 2));
if (failed.length) process.exitCode = 1;
