import table from "./data/chironEphemeris.json";

/**
 * CDI-108-01 — accurate Chiron longitude for the client / static export.
 *
 * `astronomy-engine` (the local natal engine) has no Chiron body, so Build 106/107
 * used a fixed linear model (`251.35 + days * 0.019777`) whose error routinely
 * exceeded a full 30° sign (see BUILD_108_CORE_DATA_INTEGRITY_AUDIT.md §C and
 * tests/fixtures/build108-cdi01-chiron-reference.json).
 *
 * This module replaces that with a densely-sampled Swiss Ephemeris table
 * (`data/chironEphemeris.json`, generated by `scripts/generate-chiron-ephemeris.py`
 * from pyswisseph + `seas_18.se1`) interpolated with Catmull-Rom. Validated
 * interpolation error is < 0.001° across the whole 1900–2100 span — i.e. this IS
 * real ephemeris data, not a fitted approximation.
 *
 * `chironLongitudeAt` returns `null` outside the table's safe window; callers
 * MUST fail closed (mark Chiron unavailable and preserve any stored value) — they
 * must NOT fall back to an approximation.
 */

const SAMPLES: readonly number[] = table.samples as number[]; // millidegrees, 0..359999
const START_JD_UT: number = table.startJdUt as number;
const STEP_DAYS: number = table.stepDays as number;
const N = SAMPLES.length;

/** JD (UT) for a JS Date. UT1−UTC (< 0.9 s) is negligible for a body this slow. */
export function dateToJulianDayUt(date: Date): number {
  return date.getTime() / 86_400_000 + 2_440_587.5;
}

function catmullRom(p0: number, p1: number, p2: number, p3: number, t: number): number {
  const t2 = t * t;
  const t3 = t2 * t;
  return 0.5 * (
    2 * p1
    + (-p0 + p2) * t
    + (2 * p0 - 5 * p1 + 4 * p2 - p3) * t2
    + (-p0 + 3 * p1 - 3 * p2 + p3) * t3
  );
}

/** Bring `val` within ±180° of `ref` so cubic interpolation stays continuous across 0/360. */
function unwrapNear(ref: number, val: number): number {
  let v = val;
  while (v - ref > 180) v -= 360;
  while (v - ref < -180) v += 360;
  return v;
}

/**
 * Geocentric apparent tropical ecliptic longitude of Chiron (degrees, 0..360)
 * for the given UTC instant, or `null` outside the table's safe interpolation
 * window (currently ~1900-01-15 .. 2099-12-25).
 */
export function chironLongitudeAt(date: Date): number | null {
  const jd = dateToJulianDayUt(date);
  if (!Number.isFinite(jd)) return null;
  const x = (jd - START_JD_UT) / STEP_DAYS;
  const i = Math.floor(x);
  if (i < 1 || i > N - 3) return null;
  const frac = x - i;
  const p1 = SAMPLES[i] / 1000;
  const p0 = unwrapNear(p1, SAMPLES[i - 1] / 1000);
  const p2 = unwrapNear(p1, SAMPLES[i + 1] / 1000);
  const p3 = unwrapNear(p1, SAMPLES[i + 2] / 1000);
  const lon = catmullRom(p0, p1, p2, p3, frac);
  return ((lon % 360) + 360) % 360;
}

/** True when Chiron's apparent motion is retrograde at the given instant. */
export function chironIsRetrograde(date: Date): boolean | null {
  const now = chironLongitudeAt(date);
  const prev = chironLongitudeAt(new Date(date.getTime() - 86_400_000));
  if (now === null || prev === null) return null;
  let delta = now - prev;
  if (delta > 180) delta -= 360;
  if (delta < -180) delta += 360;
  return delta < 0;
}

export const CHIRON_EPHEMERIS_META = {
  source: String(table.source),
  frame: String(table.frame),
  zodiac: String(table.zodiac),
  coverageUtc: table.coverageUtc as [string, string],
  stepDays: STEP_DAYS,
  sampleCount: N,
} as const;
